[package]
name = "TestBalance"
type = "contract"
authors = [""]
compiler_version = ">=0.18.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages", tag="aztec-packages-v0.28.1", directory="noir-projects/aztec-nr/aztec" }
value_note = { git="https://github.com/AztecProtocol/aztec-packages", tag="aztec-packages-v0.28.1", directory="noir-projects/aztec-nr/value-note" }
easy_private_state = { git="https://github.com/AztecProtocol/aztec-packages", tag="aztec-packages-v0.28.1", directory="noir-projects/aztec-nr/easy-private-state" }
compressed_string = { git="https://github.com/AztecProtocol/aztec-packages", tag="aztec-packages-v0.28.1", directory="noir-projects/aztec-nr/compressed-string" }